# Generated by Django 4.2.25 on 2025-11-06 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AssetView', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shot',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='frame_or_time',
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='h',
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='media',
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='note',
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='w',
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='x',
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='y',
        ),
        migrations.RemoveField(
            model_name='mediaasset',
            name='frame_end',
        ),
        migrations.RemoveField(
            model_name='mediaasset',
            name='frame_start',
        ),
        migrations.RemoveField(
            model_name='version',
            name='author',
        ),
        migrations.AddField(
            model_name='annotation',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='cache/annotations/'),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='frame_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='kind',
            field=models.CharField(choices=[('video', 'Video'), ('image', 'Image'), ('sequence', 'Sequence')], max_length=16),
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='width',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='code',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='shot',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='version',
            name='shot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AssetView.shot'),
        ),
        migrations.AlterField(
            model_name='version',
            name='status',
            field=models.CharField(choices=[('wip', 'WIP'), ('needs_fix', 'Needs Fix'), ('approved', 'Approved'), ('blocked', 'Blocked')], default='wip', max_length=16),
        ),
        migrations.CreateModel(
            name='ReviewStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(max_length=16)),
                ('new_status', models.CharField(max_length=16)),
                ('comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='AssetView.version')),
            ],
        ),
        migrations.CreateModel(
            name='NoteThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at_frame', models.IntegerField(blank=True, null=True)),
                ('at_time', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='threads', to='AssetView.mediaasset')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='AssetView.version')),
            ],
        ),
        migrations.CreateModel(
            name='NoteMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='AssetView.notethread')),
            ],
        ),
        migrations.CreateModel(
            name='NoteAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='cache/review_attachments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='AssetView.notemessage')),
            ],
        ),
        migrations.AddField(
            model_name='annotation',
            name='thread',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='AssetView.notethread'),
        ),
    ]
