# Generated by Django 5.2.8 on 2026-01-20 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssetView', '0003_playlist_alter_annotation_options_playlistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='publish_comment',
            field=models.TextField(blank=True, default=''),
        ),
    ]
